"""
Alerts routes: serve actionable alerts generated by the agent pipeline.
"""
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from typing import List

from app.db.session import get_db
from app.api.deps import get_current_user
from app.db.models import User

router = APIRouter(prefix="/api/alerts", tags=["alerts"])


@router.get("", response_model=List[dict])
async def get_alerts(
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get actionable alerts for the current user.

    Alerts are generated by the Connection Agent during digest creation.
    In MVP, alerts are embedded in the digest output.
    A dedicated alerts table will be added in a future iteration.
    """
    # MVP placeholder: return empty list
    # In Phase 3, this will pull from an alerts table
    return []